owner: DeclanChidlow
repo: status

sites:
  - name: Vale.Rocks
    url: https://vale.rocks
  - name: Fedi
    url: https://fedi.vale.rocks
  - name: Jellyfin
    url: https://jellyfin.vale.rocks
  - name: Minetest
    url: https://minetest.vale.rocks
  - name: AutoMod
    url: https://automod.vale.rocks

status-website:
  cname: status.vale.rocks
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  themeUrl: https://raw.githubusercontent.com/DeclanChidlow/status/master/assets/theme.css
  name: Status | Vale.Rocks
  introTitle: "Service Status"
  introMessage: The status of all the services hosted under the Vale.Rocks umbrella. Read more at [vale.rocks/services].
  navbar:
    - title: Home
      href: https://vale.rocks
    - title: Services
      href: https://vale.rocks/services
