owner: DeclanChidlow
repo: status

sites:
  - name: Vale.Rocks
    url: https://vale.rocks
  - name: Fedi
    url: https://fedi.vale.rocks
  - name: AutoMod Website
    url: https://automod.vale.rocks
  - name: AutoMod API
    url: https://automod.vale.rocks/api
  - name: Search
    url: https://search.vale.rocks
  - name: Jellyfin
    url: https://jellyfin.vale.rocks

status-website:
  cname: status.vale.rocks
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  themeUrl: https://status.vale.rocks/theme.css
  name: Status | Vale.Rocks
  introTitle: "Vale.Rocks Service Status"
  introMessage: The current and historical statuses of Vale.Rocks services. Learn more at [https://vale.rocks/services].
  navbar:
    - title: Home
      href: https://vale.rocks
    - title: Services
      href: https://vale.rocks/services
