owner: DeclanChidlow
repo: status

sites:
  - name: Vale.Rocks
    url: https://vale.rocks
  - name: Fedi
    url: https://fedi.vale.rocks
  - name: AutoMod Website
    url: https://automod.vale.rocks
  - name: AutoMod Bot
    url: https://automod.vale.rocks/dashboard
  - name: Jellyfin
    url: https://jellyfin.vale.rocks

status-website:
  cname: status.vale.rocks
  logoUrl: https://vale.rocks/assets/favicon.svg
  themeUrl: https://status.vale.rocks/theme.css
  name: Status | Vale.Rocks
  introTitle: "Vale's Service Status"
  introMessage: The current and historical statuses of Vale.Rocks services.
  customHeadHtml: "<meta name='color-scheme' content='light dark'><meta name='theme-color' content='oklch(94.75% 0.04 73)' media='(prefers-color-scheme: light)'><meta name='theme-color' content='oklch(18% 0.003 17.5)' media='(prefers-color-scheme: dark)'><link rel='preload' href='https://vale.rocks/assets/typefaces/WorkSans.woff2' as='font' type='font/woff2' crossorigin>"
  navbar:
    - title: Vale.Rocks
      href: https://vale.rocks
  skipDescriptionUpdate: true
  skipTopicsUpdate: true
